### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by riesters** [BiggerGreen/InsanityCraft#17]
how do i compile the mod to play it?

**Comment by BiggerGreen** [comment]
The mod can be downloaded from CurseForge. The code here is only made available for people to open in a coding environment and contribute things to the mod, it's not meant to be played as we probably haven't properly bug tested all of the code posted here, except in rare instances where it's been pulled specifically for the devs to compile into a finalized release build.

**Comment by riesters** [comment]
Ok

**Comment by riesters** [comment]
What is the curseforge link?

**Comment by BiggerGreen** [comment]
https://www.curseforge.com/minecraft/mc-mods/insanitycraft
